version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fileshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saini@123
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Nginx configuration    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
